### ISSUE TITLE
WARN is acceptable for Log4Net IMO

### ISSUE THREAD

**Issue by darrenferguson** [prjseal/Our.Umbraco.HealthChecks#22]
**Is your feature request related to a problem? Please describe.**
The Log4net Azure Healthcheck only accepts a value of error. Error/Warn are probably acceptable for production.

**Describe the solution you'd like**
The check should be updated so it accepts either Error or Warn.

**Comment by darrenferguson** [comment]
This is a placeholder for a PR

**Comment by prjseal** [comment]
Closed as already fixed in a PR and merged
