### ISSUE TITLE
Content Versions Healthcheck

### ISSUE THREAD

**Issue by marcemarc** [prjseal/Our.Umbraco.HealthChecks#24]
As there is no built in versioning policy in Umbraco, each save of a page will create a version and a row in the umbraco database table. Over a period of time these versions can build up, and this can have a negative impact on the performance of the Umbraco backoffice.

Particularly if people are using Umbraco to store imported data, or record 'likes' or are updating content programatically - or perhaps there is a single 'settings' node that gets updated every day - or perhaps there are 10 - 15 saves during the creation of a News Article, but after it's published it never gets edited again or rolled back. 

So idea here is for a Content Versions  healthcheck  - it wouldn't fix a site that might have 'too many versions', there is a great package from Matt Brailsford called UnVersion that 'will' allow you to define a complicated versioning policy, the idea with this check is to a) highlight the potential problem of version build up, b) point people at unversion c) flag any ridiculous situations eg 1,000,000 versions etc.

**Comment by prjseal** [comment]
Now resolved with PR from Marc
