### ISSUE TITLE
Azure Logging Check Crash

### ISSUE THREAD

**Issue by hakudoshi23** [prjseal/Our.Umbraco.HealthChecks#29]
**Is your feature request related to a problem?**

After installing the Extension with NuGet, the "Azure Logging Check" crashes every time. After cloning the repository it seems that the "CurrentValue" variable in the "AzureLoggingCheck" has a null value.

Exact location of the crash: https://github.com/prjseal/Our.Umbraco.HealthChecks/blob/master/src/Our.Umbraco.HealthChecks/Checks/Azure/AzureLoggingCheck.cs#L49

**Describe the solution you'd like**

Check for null would solve the issue, using null-propagation is the simplest solution that I could come up with:

`CurrentValue?.ToLower()`

I'll make a pull request with this fix.

**Comment by prjseal** [comment]
Fixed in #30
