### ISSUE TITLE
Could not find file 'E:\dev\Our.Umbraco.HealthChecks\src\Our.Umbraco.HealthChecks.Web\bin\roslyn\csc.exe'.

### ISSUE THREAD

**Issue by mattou07** [prjseal/Our.Umbraco.HealthChecks#31]
Hey Paul when I cloned and build this project I got a YSOD saying:
Could not find file 'E:\dev\Our.Umbraco.HealthChecks\src\Our.Umbraco.HealthChecks.Web\bin\roslyn\csc.exe'.

Doing a quick google I found this stackoverflow post: https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe

I did what the answer suggested and it fixed it for me.

**Comment by prjseal** [comment]
Cheers @mattou07

**Comment by prjseal** [comment]
It's not really an issue with the project, more a note to others who are cloning the project.
