### ISSUE TITLE
Check for an XML Sitemap

### ISSUE THREAD

**Issue by prjseal** [prjseal/Our.Umbraco.HealthChecks#9]

**Comment by prjseal** [comment]
Look for a sitemap at the address /sitemap.xml or look in the robots.txt file for the sitemap and check that it exists

**Comment by redmorello** [comment]
I’m currently looking into the site map check.

My intention was to check:
1) Is there a default sitemap at the location: /sitemap.xml. If there is, try and call it, and check the HttpStatusCode from the response.
2) Check if a robots.txt file exists in the root of the website.
2a) if it does exist, process it and loop through each sitemap url and check the response code as per 1)

**Comment by prjseal** [comment]
Closed as already merged in
